### ISSUE TITLE
builtin_elapsed_time_since_shown uniform bug/question

### ISSUE THREAD

**Issue by Press-OK** [Limeth/obs-shaderfilter-plus#24]
Hi there,

The uniform `builtin_elapsed_time_since_shown` added in one of the patches creates a timer which gets refreshed when _the source it's applied to_ is hidden and shown. I was wondering if it is possible to have this uniform (or a seperate one) which refreshes _when the filter itself_ is hidden and shown?

This would allow the user to "restart" the shader filter without having to hide/show the source itself, as the current implementation requires that the source will flicker off when the visibility of the source is toggled.

Thanks!

**Comment by Limeth** [comment]
Fixed in v0.3.0 by introducing a new uniform `builtin_elapsed_time_since_enabled`, which tracks time since the filter itself was shown rather than the source the filter is applied to.
It may be desirable to use the `min`imum of the two uniforms for certain effects. See [this updated example](https://github.com/Limeth/obs-shaderfilter-plus/blob/master/examples/visibility.hlsl).
